spring.application.name=Web_QLDH_DichVu
# 1. C?U HÌNH K?T N?I MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/smm_panel_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
# Tài nh? ??i l?i m?t kh?u bên d??i cho kh?p v?i MySQL trên máy em nhé:
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. C?U HÌNH HIBERNATE & JPA
# update: T? ??ng t?o b?ng m?i ho?c c?p nh?t c?t n?u Entity thay ??i (gi? nguyên data c?)
spring.jpa.hibernate.ddl-auto=update
# In câu l?nh SQL ra console ?? d? debug xem Hibernate ?ang làm gì
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. C?U HÌNH THYMELEAF
# T?t cache Thymeleaf trong lúc dev: C? s?a file HTML xong ra trình duy?t F5 là th?y thay ??i ngay, không c?n restart l?i project.
spring.thymeleaf.cache=false